# Generated by Django 4.2 on 2023-04-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dia_Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=6, verbose_name='Sexo')),
                ('fotografia', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Microciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_microciclo', models.PositiveSmallIntegerField(verbose_name='Número de microciclo')),
                ('atleta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.atleta', verbose_name='Atleta')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores_Microciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenadores_fk', models.ManyToManyField(to='entrenamientos.entrenador', verbose_name='Entrenador')),
                ('microciclo_fk', models.ManyToManyField(to='entrenamientos.microciclo', verbose_name='Microciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_fk', models.ManyToManyField(to='entrenamientos.disciplina', verbose_name='Disciplina')),
                ('entrenador_fk', models.ManyToManyField(to='entrenamientos.entrenador', verbose_name='Entrenador')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='persona_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.persona', verbose_name='Persona'),
        ),
        migrations.CreateModel(
            name='Dias_Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_entrenamiento_fk', models.ManyToManyField(to='entrenamientos.dia_entrenamiento', verbose_name='Día de entrenamiento')),
                ('ejercicios_fk', models.ManyToManyField(to='entrenamientos.ejercicio', verbose_name='Ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='dia_entrenamiento',
            name='microciclo_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.microciclo', verbose_name='Microciclo'),
        ),
        migrations.CreateModel(
            name='Atletas_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta_fk', models.ManyToManyField(to='entrenamientos.atleta', verbose_name='Atleta')),
                ('disciplina_fk', models.ManyToManyField(to='entrenamientos.disciplina', verbose_name='Disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='persona_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.persona', verbose_name='Persona'),
        ),
    ]
