# Generated by Django 4.2 on 2023-04-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dias_ejercicios',
            name='escala',
            field=models.CharField(choices=[('RPE', 'RPE'), ('%RM', '%RM'), ('RIR', 'RIR')], default='', max_length=3, verbose_name='Escala de entrenamiento'),
        ),
        migrations.AddField(
            model_name='dias_ejercicios',
            name='intensidad',
            field=models.CharField(default='', max_length=10, verbose_name='Intensidad'),
        ),
        migrations.AddField(
            model_name='dias_ejercicios',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='dias_ejercicios',
            name='repeticiones',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Repeticiones'),
        ),
        migrations.AddField(
            model_name='dias_ejercicios',
            name='series',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Series'),
        ),
    ]
