# Generated by Django 4.2 on 2023-05-05 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0004_remove_dias_ejercicios_dias_entrenamiento_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenadores_Microciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.entrenador', verbose_name='Entrenador')),
                ('microciclo_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.microciclo', verbose_name='Microciclo')),
            ],
            options={
                'db_table': 'entrenador_microciclo',
            },
        ),
        migrations.CreateModel(
            name='Entrenadores_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.disciplina', verbose_name='Disciplina')),
                ('entrenador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.entrenador', verbose_name='Entrenador')),
            ],
            options={
                'db_table': 'entrenador_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Dias_Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveSmallIntegerField(verbose_name='Series')),
                ('repeticiones', models.PositiveSmallIntegerField(verbose_name='Repeticiones')),
                ('escala', models.CharField(choices=[('RPE', 'RPE'), ('%RM', '%RM'), ('RIR', 'RIR')], max_length=3, verbose_name='Escala de entrenamiento')),
                ('intensidad', models.CharField(max_length=10, verbose_name='Intensidad')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('dias_entrenamiento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.dia_entrenamiento', verbose_name='Día de entrenamiento')),
                ('ejercicio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.ejercicio', verbose_name='Ejercicio')),
            ],
            options={
                'db_table': 'dias_entrenamiento_ejercicio',
            },
        ),
        migrations.CreateModel(
            name='Atletas_Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.atleta', verbose_name='Atleta')),
                ('disciplina_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.disciplina', verbose_name='Disciplina')),
            ],
            options={
                'db_table': 'atletas_disciplina',
            },
        ),
    ]
