# Generated by Django 4.2 on 2023-05-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0005_entrenadores_microciclo_entrenadores_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microciclo',
            name='titulo',
            field=models.CharField(default='sin título', max_length=255, verbose_name='Título'),
        ),
    ]
