# Generated by Django 4.2 on 2023-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0006_microciclo_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dias_ejercicios',
            old_name='ejercicio_fk',
            new_name='ejercicios_fk',
        ),
        migrations.AlterField(
            model_name='microciclo',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
